version: "3.9"


services:

  dashboard:

    build: .

    container_name: tor_cti_dashboard


    ports:

      - "8501:8501"


    volumes:

      - ./data:/app/data


    restart: unless-stopped



  crawler:


    build: .


    container_name: tor_cti_crawler


    command:

      python3 core/crawler.py


    volumes:

      - ./data:/app/data


    restart: "no"
